### ISSUE TITLE
[기능수정]/자바스크립트 작동/ Console.log가 제대로 작동하지 않는 버그

### ISSUE THREAD

**Issue by LyleSeungju** [KakaoTech-team20/dev-guidelines#24]
### 이슈 설명
- 발생한 이슈의 코드
```
let test  = 0;
if(!test){
    console.log(test);
}
```

- 작동 의도
 test 값이 0일때 출력하도록 의도하였다
### 재현 방법

- 문제를 재현하는 단계
 1. 크롬에 접속
 2. 개발자 도구 열고
 3. console창에서 출력되는 결과물 확인

### 예상결과 & 실제결과
- 예상했던 결과 
출력 : 0
- 실제로 나온 결과
출력: 0

**Comment by glwtr22** [comment]
0으로 잘 나오는데 왜 이슈로 하신건지 궁금합니다!!~!~!~~!

**Comment by jeong617** [comment]
잘 나옵니다아ㅏ~~~
