### ISSUE TITLE
[버그수정]/햄버거추천/햄버거 추천이 안뜨는 버그

### ISSUE THREAD

**Issue by glwtr22** [KakaoTech-team20/dev-guidelines#25]
### 이슈 설명
- 발생한 이슈의 코드
burgerRecommend.js 파일

- 요청 데이터
데이터

- 버그 내용
햄버거 추천이 안돼요 

- 작동 의도
추천이 되도록

### 재현 방법
- 어떤 환경에서 문제가 발생했는지(ex. 브라우저, OS 등)
브라우저 환경

- 문제를 재현하는 단계
재현하는 단계??

### 예상결과 & 실제결과
- 예상했던 결과
추천이 되게!!!

- 실제로 나온 결과
추천이 안돼

### 스크린샷(선택)
- 관련 스크린샷(ex. 에러 메세지 등)
jpgjpg

### 추가정보(선택)
- 로그 파일, 시스템 설정 등
...

- 또는 그 외 전달사항 또는 참고정보
해결이 필요합니다!!!

**Comment by glwtr22** [comment]
**주석**은 안보이는군요 !

**Comment by jeong617** [comment]
햄버거 먹고싶어요

**Comment by LyleSeungju** [comment]
추천이 비즈로직이 제대로 적용되었는지 해당 코드의 백엔드 서버를 확인 해보겠습니다.

**Comment by hjlim4u** [comment]
확인 완료했습니다.

**Comment by glwtr22** [comment]
해결 감사합니다 ><><
