### ISSUE TITLE
[디자인변경]/반응형웹/모바일 화면에서 깨지는 버그

### ISSUE THREAD

**Issue by jeong617** [KakaoTech-team20/dev-guidelines#26]
### 이슈 설명
- 발생한 이슈의 코드
``` css
@media ...
```

- 버그 내용 : ~~페이지 모바일에서 반응형 웹이 요상합니다아

### 재현 방법

mac chrome 환경

### 예상결과 & 실제결과

예상 결과 : 예쁜 화면
실제 결과 : 이상한 화면 ㅠㅠ

**Comment by glwtr22** [comment]
예뻐요~ ~

**Comment by LyleSeungju** [comment]
동일한 환경에서 깨지지 않도록 모바일 개발 환경을 조성하겠습니다!
