### ISSUE TITLE
[버그 수정]/앱푸시/SFTP파일전송 모듈 수정

### ISSUE THREAD

**Issue by hjlim4u** [KakaoTech-team20/dev-guidelines#27]
### 발생한 이슈 코드

```javascript
worker.addFunction('apppush', (job) => {
..
  var module = new sftpfilemonitoringworker();
}
```

sftpfilemonitoring woker 명 변경에 따른 모듈 임포트 에러

변경된 워커로 임포트
### 재현 방법

브라우저

### 예상결과 & 실제결과

파일 모니터링 결과 임포트

임포트 에러

**Comment by glwtr22** [comment]
모듈 임포트를 잘 합시다 ~ ~

**Comment by LyleSeungju** [comment]
해당 환경이 정상적으로 작동하는지 테스트 해보았으나 이런이런 방법에서 문제일수 있으니 깃 액션에 올려두겠습니다.

**Comment by jeong617** [comment]
깃 액션 확인해보겠습니다아~~~

**Comment by whdms2008** [comment]
WTF
